---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixy.
--- DateTime: 18-12-5 下午4:44
---

local _M = {}

function _M.test()
    ngx.log(ngx.ERR, ">>>>>>>>>")
    return "AHA"
end

return _M