---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lixy.
--- DateTime: 18-12-5 下午5:20
---

local cjson = require("cjson")-- JSON解析库

local _M = {}

--[[
    解析请求参数
]]
function _M.get_args()
    -- 判断当前请求类型： GET/POST
    local method = ngx.req.get_method()

    if method == "GET" then -- 解析 GET 请求参数
        return ngx.req.get_uri_args()
    elseif method == "POST" then -- 解析 POST 请求参数
        ngx.req.read_body()
        local body = ngx.req.get_body_data()
    end

end

--[[
    检查参数，检查关键key参数是否存在于参数table表中
    @params:
        args: 参数表(table) 如： {id=100, type=1}
        keys: 关键key(数组) 如： {"id", "type"}
    @return:
        $1: 检查状态： true：检查的参数存在于参数表中; nil: 有参数不存在 或 参数表为nil 或关键key为nil
        $2: 错误信息
]]
function _M.check_keys(args, keys)
    if not args or not keys then
        return nil
    end
    local errmsg = ""
    for k,v in pairs(keys) do
        if not args[k] then
            if errmsg ~= "" then
                errmsg = k
            end
            errmsg = errmsg .. ", " .. k
        end
    end
    if errmsg ~= "" then
        return nil, "[" .. errmsg .. "]不存在"
    end
    return true
end

--[[
    发送HTTP请求
]]
function _M.http()

end

--[[
    请求访问内部子接口 （CAPTURE）
    @params:
        method: 请求方式： ngx.HTTP_GET / ngx.HTTP_POST
        url: 接口地址 如： /modules/test/getdata.do
]]
function _M.capture(method, url, params)
    ngx.location.capture(url, {
        method = method,
        body = "id=1001&type=1"
    })
end


--[[
    返回数据给网络请求方，数据格式为JSON字符串 如: {code=200, msg="SUCCESS", data={status=1, name="hello"}} （JSON转换成字符串）
    @params:
        code: 错误码
        msg： 描述信息
        data: 返回数据体
    @return: nil
]]
function _M.say(code, msg, data)
    ngx.say(cjson.encode({code=code,msg=msg,data=data}))
    return
end

return _M